version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://dev_user:dev_pass@mongodb:27017/
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:7.0.2-ubi9
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev_user
      - MONGO_INITDB_ROOT_PASSWORD=dev_pass
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
